export const ORDER_REPOSITORY = Symbol('ORDER_REPOSITORY');
export const ORDER_SERVICE = Symbol('ORDER_SERVICE');
export const ORDER_ITEM_REPOSITORY = Symbol('ORDER_ITEM_REPOSITORY');
export const ORDER_ITEM_SERVICE = Symbol('ORDER_ITEM_SERVICE');
export const ORDER_COUPON_REPOSITORY = Symbol('ORDER_COUPON_REPOSITORY');
export const ORDER_COUPON_SERVICE = Symbol('ORDER_COUPON_SERVICE');