export const TOKEN_REPOSITORY = Symbol('TOKEN_REPOSITORY');
export const TOKEN_SERVICE = Symbol('TOKEN_SERVICE');
export const TOKEN_ACTIVATION_REPOSITORY = Symbol('TOKEN_ACTIVATION_REPOSITORY');
export const AUTHENTICATIONLOG_REPOSITORY = Symbol('AUTHENTICATIONLOG_REPOSITORY');
